import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          Norman Teodoro
        </h1>

        <p className={styles.description}>
          Web Developer{' '}
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Projects &rarr;</h2>
            <p>My projects goe  here</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Skills &rarr;</h2>
            <p>My skills go here</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Links &rarr;</h2>
            <p>Github | LinkedIn</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Resumé &rarr;</h2>
            <p>
              Download my resumé
            </p>
          </a>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
